# Generated by Django 5.0.1 on 2024-01-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idIdioma', models.AutoField(db_column='idIdioma', primary_key=True, serialize=False)),
                ('prefijo', models.CharField(db_column='prefijo', max_length=5)),
                ('idioma', models.CharField(db_column='idioma', max_length=50)),
            ],
            options={
                'db_table': 'tbl_idiomas',
            },
        ),
    ]
